# Generated by Django 3.0.11 on 2020-11-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('new', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('posted_at', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('listing', models.ManyToManyField(to='posts.Post')),
            ],
            options={
                'verbose_name': 'tool',
                'verbose_name_plural': 'tools',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('listing', models.ManyToManyField(to='posts.Post')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
    ]
