# Generated by Django 3.0.11 on 2020-11-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201110_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='listing',
            field=models.ManyToManyField(blank=True, null=True, related_name='languages', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='listing',
            field=models.ManyToManyField(blank=True, null=True, related_name='tools', to='posts.Post'),
        ),
    ]
