# Generated by Django 3.0.11 on 2020-11-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201111_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['name'], 'verbose_name': 'tool', 'verbose_name_plural': 'tools'},
        ),
    ]
